IdentityApplication/Controllers/IdentityUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IdentityApplication.Context;
using IdentityApplication.Models;
using Microsoft.AspNetCore.Authorization;

namespace IdentityApplication.Controllers
{
    [Authorize]
    public class IdentityUserController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IdentityUserController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: IdentityUser
        public async Task<IActionResult> Index()
        {
              return _context.IdentityModel != null ? 
                          View(await _context.IdentityModel.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.IdentityModel'  is null.");
        }

        // GET: IdentityUser/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.IdentityModel == null)
            {
                return NotFound();
            }

            var identityModel = await _context.IdentityModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (identityModel == null)
            {
                return NotFound();
            }

            return View(identityModel);
        }

        // GET: IdentityUser/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: IdentityUser/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Mobile,Email,Soruces")] IdentityModel identityModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(identityModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(identityModel);
        }

        // GET: IdentityUser/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.IdentityModel == null)
            {
                return NotFound();
            }

            var identityModel = await _context.IdentityModel.FindAsync(id);
            if (identityModel == null)
            {
                return NotFound();
            }
            return View(identityModel);
        }

        // POST: IdentityUser/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Mobile,Email,Soruces")] IdentityModel identityModel)
        {
            if (id != identityModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(identityModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IdentityModelExists(identityModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(identityModel);
        }

        // GET: IdentityUser/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.IdentityModel == null)
            {
                return NotFound();
            }

            var identityModel = await _context.IdentityModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (identityModel == null)
            {
                return NotFound();
            }

            return View(identityModel);
        }

        // POST: IdentityUser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.IdentityModel == null)
            {
                return Problem("Entity set 'ApplicationDbContext.IdentityModel'  is null.");
            }
            var identityModel = await _context.IdentityModel.FindAsync(id);
            if (identityModel != null)
            {
                _context.IdentityModel.Remove(identityModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IdentityModelExists(int id)
        {
          return (_context.IdentityModel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

IdentityApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />  
    <link rel="stylesheet" href="~/IdentityApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IdentityApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="IdentityUser" asp-action="Index">Identity</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_loginPartial"/>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - IdentityApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>